version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
