version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - cyclop
    - gosec
    - gocritic
    - gocyclo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocognit
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - unparam
    - usetesting
    - usestdlibvars
    - varnamelen
    - wastedassign
    - wrapcheck
