version: "2"

# Run configuration
run:
  timeout: 5m
  go: "1.25"
  tests: true
  allow-parallel-runners: true
  skip-dirs:
    - vendor
    - .git
    - .github

  modules-download-mode: readonly

# Output configuration
output:
  format: colored-line-number
  sort-results: true

# Linters configuration
linters:
  disable-all: true
  enable:
    # Essential linters
    - errcheck # Check for unchecked errors
    - gosec # Security-focused linter
    - govet # Examines Go source code and reports suspicious constructs
    - staticcheck # Go static analysis
    - unused # Checks for unused constants, variables, functions and types

    # Code quality
    - ineffassign # Detects ineffectual assignments
    - misspell # Finds commonly misspelled English words

    # Best practices
    - bodyclose # Checks whether HTTP response body is closed
    - contextcheck # Check whether the function uses a non-inherited context
    - durationcheck # Check for two durations multiplied together
    - errname # Checks that sentinel errors are prefixed with Err
    - errorlint # Find code that will cause problems with error wrapping
    - exhaustive # Check exhaustiveness of enum switch statements
    - gochecknoinits # Checks that no init functions are present
    - goconst # Finds repeated strings that could be replaced by a constant
    - gocyclo # Computes and checks cyclomatic complexity
    - nolintlint # Reports ill-formed or insufficient nolint directives
    - predeclared # Find code that shadows predeclared identifiers
    - thelper # Detects test helpers without t.Helper() call
    - unconvert # Remove unnecessary type conversions
    - unparam # Reports unused function parameters
    - whitespace # Tool for detection of leading and trailing whitespace

# Linters settings
linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: false

  govet:
    check-shadowing: true
    check-unreachable: true
    check-rangeloops: true

  gocyclo:
    min-complexity: 10

  staticcheck:
    checks: ["all"]

  gosec:
    severity: medium
    confidence: medium

# Issues configuration
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Allow err assignment in test code
    - path: "_test\\.go"
      linters:
        - unparam
    # Allow init functions in main
    - path: "cmd/.*\\.go"
      linters:
        - gochecknoinits
