run:
  timeout: 5m
  go: "1.25"
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    # Default linters
    - errcheck # Check for unchecked errors
    - gofmt # Check code formatting
    - goimports # Check import formatting
    - gosec # Security-focused linter
    - govet # Examines Go source code and reports suspicious constructs
    - ineffassign # Detects ineffectual assignments
    - misspell # Finds commonly misspelled English words
    - staticcheck # Go static analysis
    - unused # Checks for unused constants, variables, functions and types

    # Additional recommended linters
    - bodyclose # Checks whether HTTP response body is closed
    - contextcheck # Check whether the function uses a non-inherited context
    - durationcheck # Check for two durations multiplied together
    - errname # Checks that sentinel errors are prefixed with Err
    - errorlint # Find code that will cause problems with error wrapping
    - exhaustive # Check exhaustiveness of enum switch statements
    - exportloopref # Checks for pointers to enclosing loop variables
    - gochecknoinits # Checks that no init functions are present
    - goconst # Finds repeated strings that could be replaced by a constant
    - gocritic # Provides diagnostics that check for bugs, performance and style issues
    - godot # Check if comments end in a period
    - gocyclo # Computes and checks cyclomatic complexity
    - goprintffuncname # Checks that printf-like functions are named with f at the end
    - gosimple # Linter for Go source code that specializes in simplifying code
    - nolintlint # Reports ill-formed or insufficient nolint directives
    - predeclared # Find code that shadows predeclared identifiers
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - stylecheck # Stylecheck is a replacement for golint
    - thelper # Detects test helpers without t.Helper() call
    - unconvert # Remove unnecessary type conversions
    - unparam # Reports unused function parameters
    - whitespace # Tool for detection of leading and trailing whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow # Too strict for general use

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult # Allow unnamed results

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - dupl
        - gosec
    - path: cmd/
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0
