run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/
      linters:
        - errcheck
