language: python

python:
  - "3.6"
  - "nightly" # currently points to 3.7-dev

# command to run tests
script:
  - cd $TRAVIS_BUILD_DIR
  - ./vulncontrol.py
  - ./vulncontrol.py 376032419:AAGef5V0q96x7igp5xxvcFTaOZzGXaMdEfk 281724312
