name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - run: go mod download
      - run: go test -v ./...
      - run: go vet ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - run: |
          VERSION=${GITHUB_REF#refs/tags/}
          go build -ldflags="-X cvewatch/pkg/version.Version=$VERSION -s -w" -o cvewatch ./cmd/cvewatch
          GOOS=linux GOARCH=amd64 go build -ldflags="-X cvewatch/pkg/version.Version=$VERSION -s -w" -o cvewatch-linux-amd64 ./cmd/cvewatch
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X cvewatch/pkg/version.Version=$VERSION -s -w" -o cvewatch-darwin-amd64 ./cmd/cvewatch
          GOOS=windows GOARCH=amd64 go build -ldflags="-X cvewatch/pkg/version.Version=$VERSION -s -w" -o cvewatch-windows-amd64.exe ./cmd/cvewatch

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cvewatch-linux-amd64
            cvewatch-darwin-amd64
            cvewatch-windows-amd64.exe
          body: |
            ## CVEWatch ${{ github.ref_name }}

            ### What's New
            - Complete Go rewrite from Python
            - NVD API v2.0 integration
            - Modern YAML-based configuration
            - Multiple output formats
            - Product-based filtering with CPE patterns
            - CVSS score filtering and severity mapping
            - Comprehensive testing and benchmarking
            - Simplified CI/CD pipeline

            ### Breaking Changes
            - Configuration format changed from products.txt to YAML
            - Command-line interface completely redesigned
            - API endpoints changed from cvedetails.com to NVD
            - Python dependencies no longer required

            ### Downloads
            - Linux AMD64: cvewatch-linux-amd64
            - macOS AMD64: cvewatch-darwin-amd64
            - Windows AMD64: cvewatch-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
